<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.kt.enrollez.Broker_Dashbaord" tests="12" time="35.045" ignored="0" failures="2" timestamp="14 Dec 2019 05:11:47 GMT" skipped="0" hostname="SUBHASHA-PC" errors="0">
  <testcase name="CountSummary_Tab" time="0.281" classname="com.kt.enrollez.Broker_Dashbaord">
    <failure type="java.lang.AssertionError" message="expected [Count Summary] but found []">
      <![CDATA[java.lang.AssertionError: expected [Count Summary] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.kt.enrollez.Broker_Dashbaord.CountSummary_Tab(Broker_Dashbaord.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- CountSummary_Tab -->
  <testcase name="Activity_Tab" time="0.318" classname="com.kt.enrollez.Broker_Dashbaord">
    <failure type="java.lang.AssertionError" message="expected [Search] but found [Search
All
Keyword
Date]">
      <![CDATA[java.lang.AssertionError: expected [Search] but found [Search
All
Keyword
Date]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.kt.enrollez.Broker_Dashbaord.Activity_Tab(Broker_Dashbaord.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- Activity_Tab -->
  <testcase name="Verify_UserList_link" time="1.803" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_BrokerRep_link" time="3.648" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_SearchEmployee_link" time="2.283" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_AddEmployer_link" time="2.505" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_SearchEmployer_link" time="1.881" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_Details_link" time="5.343" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_Credentials_link" time="2.086" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_Login_WithValidInputs" time="12.166" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Verify_EmployerList_link" time="2.328" classname="com.kt.enrollez.Broker_Dashbaord"/>
  <testcase name="Employer_Tab" time="0.403" classname="com.kt.enrollez.Broker_Dashbaord"/>
</testsuite> <!-- com.kt.enrollez.Broker_Dashbaord -->
